In [1]:
import pandas as pd
import numpy as np

print("Dataset environment ready ✅")

Dataset environment ready ✅

In [2]:
# Create machine information

machines = pd.DataFrame({
    "machine_id": ["M001", "M002", "M003", "M004", "M005"],
    
    "type": [
        "CNC",
        "CNC",
        "Press",
        "Lathe",
        "Milling"
    ],
    
    "age": [
        2,
        5,
        3,
        7,
        1
    ],
    
    "rated_capacity": [
        100,
        120,
        150,
        90,
        110
    ],
    
    "power_rating": [
        50,
        60,
        70,
        45,
        55
    ],
    
    "installation_date": [
        "2024-01-15",
        "2021-06-10",
        "2023-03-20",
        "2019-09-05",
        "2025-02-12"
    ]
})

machines

  machine_id     type  age  rated_capacity  power_rating installation_date
0       M001      CNC    2             100            50        2024-01-15
1       M002      CNC    5             120            60        2021-06-10
2       M003    Press    3             150            70        2023-03-20
3       M004    Lathe    7              90            45        2019-09-05
4       M005  Milling    1             110            55        2025-02-12

In [3]:
# Check our machine data

print("Number of machines:", len(machines))
print("\nMachine information:")
display(machines)

Number of machines: 5

Machine information:

  machine_id     type  age  rated_capacity  power_rating installation_date
0       M001      CNC    2             100            50        2024-01-15
1       M002      CNC    5             120            60        2021-06-10
2       M003    Press    3             150            70        2023-03-20
3       M004    Lathe    7              90            45        2019-09-05
4       M005  Milling    1             110            55        2025-02-12

In [4]:
# Generate synthetic daily operations data

np.random.seed(42)

dates = pd.date_range(
    start="2026-01-01",
    end="2026-06-30",
    freq="D"
)

shifts = ["Shift-1", "Shift-2", "Shift-3"]

operations = []

for date in dates:
    for _, machine in machines.iterrows():
        for shift in shifts:

            # Random operating conditions
            runtime = np.random.uniform(5.5, 8.0)
            downtime = 8.0 - runtime

            # Expected production is based on runtime and machine capacity
            expected_output = runtime * machine["rated_capacity"]

            # Small production variation
            production_factor = np.random.normal(0.95, 0.05)

            actual_output = expected_output * production_factor

            # Energy is related to runtime and machine power
            energy_kwh = runtime * machine["power_rating"]
            energy_kwh *= np.random.normal(1.0, 0.05)

            # Scrap is a small percentage of production
            scrap_units = actual_output * np.random.uniform(0.01, 0.04)

            operations.append({
                "date": date,
                "machine_id": machine["machine_id"],
                "shift": shift,
                "runtime": round(runtime, 2),
                "downtime": round(downtime, 2),
                "expected_output": round(expected_output, 2),
                "actual_output": round(actual_output, 2),
                "energy_kwh": round(energy_kwh, 2),
                "scrap_units": round(scrap_units, 2)
            })

daily_operations = pd.DataFrame(operations)

print("Daily operations created successfully! ✅")
print("Number of records:", len(daily_operations))

display(daily_operations.head(10))

Daily operations created successfully! ✅
Number of records: 2715

,date,machine_id,shift,runtime,downtime,expected_output,actual_output,energy_kwh,scrap_units
0,2026-01-01,M001,Shift-1,6.44,1.56,643.64,575.67,326.95,8.45
1,2026-01-01,M001,Shift-2,5.65,2.35,564.52,544.17,296.52,17.00
2,2026-01-01,M001,Shift-3,5.55,2.45,555.15,511.27,270.28,7.93
3,2026-01-01,M002,Shift-1,6.26,1.74,751.27,615.57,393.49,11.53
4,2026-01-01,M002,Shift-2,7.03,0.97,843.56,783.32,406.12,16.44
5,2026-01-01,M002,Shift-3,6.64,1.36,796.82,731.90,410.32,18.61
6,2026-01-01,M003,Shift-1,6.98,1.02,1047.16,1001.20,476.08,15.13
7,2026-01-01,M003,Shift-2,5.66,2.34,849.39,781.43,415.16,10.10
8,2026-01-01,M003,Shift-3,7.21,0.79,1081.59,972.26,500.66,24.17
9,2026-01-01,M004,Shift-1,5.59,2.41,502.74,471.83,256.26,14.10

In [5]:
# Look at the first 10 records

display(daily_operations.head(10))

,date,machine_id,shift,runtime,downtime,expected_output,actual_output,energy_kwh,scrap_units
0,2026-01-01,M001,Shift-1,6.44,1.56,643.64,575.67,326.95,8.45
1,2026-01-01,M001,Shift-2,5.65,2.35,564.52,544.17,296.52,17.00
2,2026-01-01,M001,Shift-3,5.55,2.45,555.15,511.27,270.28,7.93
3,2026-01-01,M002,Shift-1,6.26,1.74,751.27,615.57,393.49,11.53
4,2026-01-01,M002,Shift-2,7.03,0.97,843.56,783.32,406.12,16.44
5,2026-01-01,M002,Shift-3,6.64,1.36,796.82,731.90,410.32,18.61
6,2026-01-01,M003,Shift-1,6.98,1.02,1047.16,1001.20,476.08,15.13
7,2026-01-01,M003,Shift-2,5.66,2.34,849.39,781.43,415.16,10.10
8,2026-01-01,M003,Shift-3,7.21,0.79,1081.59,972.26,500.66,24.17
9,2026-01-01,M004,Shift-1,5.59,2.41,502.74,471.83,256.26,14.10

In [6]:
# Check number of rows and columns

print("Rows:", daily_operations.shape[0])
print("Columns:", daily_operations.shape[1])

Rows: 2715
Columns: 9

In [7]:
# Check for missing values

daily_operations.isnull().sum()

date               0
machine_id         0
shift              0
runtime            0
downtime           0
expected_output    0
actual_output      0
energy_kwh         0
scrap_units        0
dtype: int64

In [8]:
# Summary of our numerical data

daily_operations.describe()

,date,runtime,downtime,expected_output,actual_output,energy_kwh,scrap_units
count,2715,2715.000000,2715.000000,2715.000000,2715.000000,2715.000000,2715.000000
mean,2026-04-01 00:00:00,6.726762,1.273238,767.013562,728.354063,376.421168,18.095190
min,2026-01-01 00:00:00,5.500000,0.000000,495.590000,411.800000,228.080000,4.650000
25%,2026-02-15 00:00:00,6.085000,0.655000,645.720000,608.220000,321.625000,12.070000
50%,2026-04-01 00:00:00,6.720000,1.280000,738.180000,698.620000,367.810000,17.100000
75%,2026-05-16 00:00:00,7.345000,1.915000,864.145000,825.720000,422.390000,23.035000
max,2026-06-30 00:00:00,8.000000,2.500000,1198.700000,1272.400000,611.230000,45.430000
std,NaN,0.723633,0.723633,162.987667,160.312110,73.767202,7.601793

In [9]:
# Add machine capacity and power information

daily_check = daily_operations.merge(
    machines[["machine_id", "rated_capacity", "power_rating"]],
    on="machine_id",
    how="left"
)

display(daily_check.head())

,date,machine_id,shift,runtime,downtime,expected_output,actual_output,energy_kwh,scrap_units,rated_capacity,power_rating
0,2026-01-01,M001,Shift-1,6.44,1.56,643.64,575.67,326.95,8.45,100,50
1,2026-01-01,M001,Shift-2,5.65,2.35,564.52,544.17,296.52,17.00,100,50
2,2026-01-01,M001,Shift-3,5.55,2.45,555.15,511.27,270.28,7.93,100,50
3,2026-01-01,M002,Shift-1,6.26,1.74,751.27,615.57,393.49,11.53,120,60
4,2026-01-01,M002,Shift-2,7.03,0.97,843.56,783.32,406.12,16.44,120,60

In [10]:
# Calculate expected production from runtime and machine capacity

daily_check["calculated_expected"] = (
    daily_check["runtime"] *
    daily_check["rated_capacity"]
)

display(
    daily_check[
        [
            "machine_id",
            "runtime",
            "rated_capacity",
            "expected_output",
            "calculated_expected"
        ]
    ].head(10)
)

  machine_id  runtime  rated_capacity  expected_output  calculated_expected
0       M001     6.44             100           643.64                644.0
1       M001     5.65             100           564.52                565.0
2       M001     5.55             100           555.15                555.0
3       M002     6.26             120           751.27                751.2
4       M002     7.03             120           843.56                843.6
5       M002     6.64             120           796.82                796.8
6       M003     6.98             150          1047.16               1047.0
7       M003     5.66             150           849.39                849.0
8       M003     7.21             150          1081.59               1081.5
9       M004     5.59              90           502.74                503.1

In [11]:
# Calculate expected energy from runtime and machine power

daily_check["calculated_energy"] = (
    daily_check["runtime"] *
    daily_check["power_rating"]
)

display(
    daily_check[
        [
            "machine_id",
            "runtime",
            "power_rating",
            "energy_kwh",
            "calculated_energy"
        ]
    ].head(10)
)

  machine_id  runtime  power_rating  energy_kwh  calculated_energy
0       M001     6.44            50      326.95             322.00
1       M001     5.65            50      296.52             282.50
2       M001     5.55            50      270.28             277.50
3       M002     6.26            60      393.49             375.60
4       M002     7.03            60      406.12             421.80
5       M002     6.64            60      410.32             398.40
6       M003     6.98            70      476.08             488.60
7       M003     5.66            70      415.16             396.20
8       M003     7.21            70      500.66             504.70
9       M004     5.59            45      256.26             251.55

In [12]:
# Create a separate dataset for ML features

ml_data = daily_check.copy()

print("ML feature dataset created ✅")
print("Rows:", len(ml_data))

ML feature dataset created ✅
Rows: 2715

In [13]:
# Production variance

ml_data["production_variance"] = (
    ml_data["actual_output"] -
    ml_data["expected_output"]
)

display(
    ml_data[
        [
            "expected_output",
            "actual_output",
            "production_variance"
        ]
    ].head(10)
)

   expected_output  actual_output  production_variance
0           643.64         575.67               -67.97
1           564.52         544.17               -20.35
2           555.15         511.27               -43.88
3           751.27         615.57              -135.70
4           843.56         783.32               -60.24
5           796.82         731.90               -64.92
6          1047.16        1001.20               -45.96
7           849.39         781.43               -67.96
8          1081.59         972.26              -109.33
9           502.74         471.83               -30.91

In [14]:
# Production variance percentage

ml_data["production_variance_pct"] = (
    ml_data["production_variance"] /
    ml_data["expected_output"]
) * 100

display(
    ml_data[
        [
            "expected_output",
            "actual_output",
            "production_variance_pct"
        ]
    ].head(10)
)

   expected_output  actual_output  production_variance_pct
0           643.64         575.67               -10.560251
1           564.52         544.17                -3.604832
2           555.15         511.27                -7.904170
3           751.27         615.57               -18.062747
4           843.56         783.32                -7.141164
5           796.82         731.90                -8.147386
6          1047.16        1001.20                -4.389014
7           849.39         781.43                -8.001036
8          1081.59         972.26               -10.108267
9           502.74         471.83                -6.148307

In [15]:
# Machine utilization

shift_duration = 8

ml_data["utilization_pct"] = (
    ml_data["runtime"] /
    shift_duration
) * 100

display(
    ml_data[
        [
            "runtime",
            "utilization_pct"
        ]
    ].head(10)
)

   runtime  utilization_pct
0     6.44           80.500
1     5.65           70.625
2     5.55           69.375
3     6.26           78.250
4     7.03           87.875
5     6.64           83.000
6     6.98           87.250
7     5.66           70.750
8     7.21           90.125
9     5.59           69.875

In [16]:
# Downtime rate

ml_data["downtime_rate_pct"] = (
    ml_data["downtime"] /
    shift_duration
) * 100

display(
    ml_data[
        [
            "downtime",
            "downtime_rate_pct"
        ]
    ].head(10)
)

   downtime  downtime_rate_pct
0      1.56             19.500
1      2.35             29.375
2      2.45             30.625
3      1.74             21.750
4      0.97             12.125
5      1.36             17.000
6      1.02             12.750
7      2.34             29.250
8      0.79              9.875
9      2.41             30.125

In [17]:
# Scrap rate

ml_data["scrap_rate_pct"] = (
    ml_data["scrap_units"] /
    ml_data["actual_output"]
) * 100

display(
    ml_data[
        [
            "actual_output",
            "scrap_units",
            "scrap_rate_pct"
        ]
    ].head(10)
)

   actual_output  scrap_units  scrap_rate_pct
0         575.67         8.45        1.467855
1         544.17        17.00        3.124024
2         511.27         7.93        1.551040
3         615.57        11.53        1.873061
4         783.32        16.44        2.098759
5         731.90        18.61        2.542697
6        1001.20        15.13        1.511187
7         781.43        10.10        1.292502
8         972.26        24.17        2.485961
9         471.83        14.10        2.988364

In [18]:
# Energy intensity

ml_data["energy_intensity"] = (
    ml_data["energy_kwh"] /
    ml_data["actual_output"]
)

display(
    ml_data[
        [
            "energy_kwh",
            "actual_output",
            "energy_intensity"
        ]
    ].head(10)
)

   energy_kwh  actual_output  energy_intensity
0      326.95         575.67          0.567947
1      296.52         544.17          0.544903
2      270.28         511.27          0.528644
3      393.49         615.57          0.639229
4      406.12         783.32          0.518460
5      410.32         731.90          0.560623
6      476.08        1001.20          0.475509
7      415.16         781.43          0.531282
8      500.66         972.26          0.514945
9      256.26         471.83          0.543119

In [19]:
# Check for impossible negative values

print("Negative runtime:", (ml_data["runtime"] < 0).sum())
print("Negative downtime:", (ml_data["downtime"] < 0).sum())
print("Negative expected output:", (ml_data["expected_output"] < 0).sum())
print("Negative actual output:", (ml_data["actual_output"] < 0).sum())
print("Negative energy:", (ml_data["energy_kwh"] < 0).sum())
print("Negative scrap:", (ml_data["scrap_units"] < 0).sum())

Negative runtime: 0
Negative downtime: 0
Negative expected output: 0
Negative actual output: 0
Negative energy: 0
Negative scrap: 0

In [20]:
# Check whether runtime + downtime exceeds shift duration

invalid_shift_time = ml_data[
    (ml_data["runtime"] + ml_data["downtime"]) > 8
]

print("Invalid shift records:", len(invalid_shift_time))

Invalid shift records: 0

In [21]:
# Check for duplicate records

duplicates = ml_data.duplicated().sum()

print("Duplicate records:", duplicates)

Duplicate records: 0

In [22]:
# Check date data type

print(ml_data["date"].dtype)

datetime64[us]

In [23]:
# Sort data chronologically

ml_data = ml_data.sort_values("date").reset_index(drop=True)

print("Data sorted by date ✅")
print("First date:", ml_data["date"].min())
print("Last date:", ml_data["date"].max())

Data sorted by date ✅
First date: 2026-01-01 00:00:00
Last date: 2026-06-30 00:00:00

In [24]:
# Select features (X) and target (y)

features = [
    "runtime",
    "downtime",
    "expected_output",
    "energy_kwh",
    "scrap_units"
]

X = ml_data[features]
y = ml_data["actual_output"]

print("Features (X):")
print(features)

print("\nTarget (y):")
print("actual_output")

print("\nX shape:", X.shape)
print("y shape:", y.shape)

Features (X):
['runtime', 'downtime', 'expected_output', 'energy_kwh', 'scrap_units']

Target (y):
actual_output

X shape: (2715, 5)
y shape: (2715,)

In [25]:
# Check our date range

print("First date:", ml_data["date"].min())
print("Last date:", ml_data["date"].max())
print("Total records:", len(ml_data))

First date: 2026-01-01 00:00:00
Last date: 2026-06-30 00:00:00
Total records: 2715

In [26]:
# Time-based train-test split

split_index = int(len(ml_data) * 0.8)

train_data = ml_data.iloc[:split_index]
test_data = ml_data.iloc[split_index:]

print("Training records:", len(train_data))
print("Testing records:", len(test_data))

print("\nTraining period:")
print(train_data["date"].min(), "to", train_data["date"].max())

print("\nTesting period:")
print(test_data["date"].min(), "to", test_data["date"].max())

Training records: 2172
Testing records: 543

Training period:
2026-01-01 00:00:00 to 2026-05-25 00:00:00

Testing period:
2026-05-25 00:00:00 to 2026-06-30 00:00:00

In [27]:
# Create a clean date-based train-test split

unique_dates = sorted(ml_data["date"].unique())

split_date_index = int(len(unique_dates) * 0.8)
split_date = unique_dates[split_date_index]

train_data = ml_data[ml_data["date"] < split_date]
test_data = ml_data[ml_data["date"] >= split_date]

print("Training records:", len(train_data))
print("Testing records:", len(test_data))

print("\nTraining period:")
print(train_data["date"].min(), "to", train_data["date"].max())

print("\nTesting period:")
print(test_data["date"].min(), "to", test_data["date"].max())

Training records: 2160
Testing records: 555

Training period:
2026-01-01 00:00:00 to 2026-05-24 00:00:00

Testing period:
2026-05-25 00:00:00 to 2026-06-30 00:00:00

In [28]:
# Calculate the baseline prediction

baseline_prediction = train_data["actual_output"].mean()

print("Baseline prediction:", round(baseline_prediction, 2))

Baseline prediction: 727.89

In [29]:
# Create baseline predictions for the test data

baseline_predictions = np.full(
    len(test_data),
    baseline_prediction
)

print("Number of baseline predictions:", len(baseline_predictions))

Number of baseline predictions: 555

In [30]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

baseline_mae = mean_absolute_error(
    test_data["actual_output"],
    baseline_predictions
)

baseline_rmse = np.sqrt(
    mean_squared_error(
        test_data["actual_output"],
        baseline_predictions
    )
)

print("Baseline MAE:", round(baseline_mae, 2))
print("Baseline RMSE:", round(baseline_rmse, 2))

Baseline MAE: 127.58
Baseline RMSE: 160.11

In [31]:
# Prepare training and testing features

X_train = train_data[features]
y_train = train_data["actual_output"]

X_test = test_data[features]
y_test = test_data["actual_output"]

print("X_train:", X_train.shape)
print("y_train:", y_train.shape)
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

X_train: (2160, 5)
y_train: (2160,)
X_test: (555, 5)
y_test: (555,)

In [32]:
from sklearn.linear_model import LinearRegression

# Create the model
linear_model = LinearRegression()

# Teach the model using training data
linear_model.fit(X_train, y_train)

print("Linear Regression trained successfully! ✅")

Linear Regression trained successfully! ✅

In [33]:
# Make predictions on unseen test data

linear_predictions = linear_model.predict(X_test)

print("Predictions created:", len(linear_predictions))
print("\nFirst 10 predictions:")
print(linear_predictions[:10])

Predictions created: 555

First 10 predictions:
[ 755.65382447  804.56027382  479.8450021   607.92319079  651.45990212
 1089.19275175  938.4272017   635.49145158  826.65287561  736.12404906]

In [34]:
# Evaluate Linear Regression

linear_mae = mean_absolute_error(
    y_test,
    linear_predictions
)

linear_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        linear_predictions
    )
)

print("Linear Regression MAE:", round(linear_mae, 2))
print("Linear Regression RMSE:", round(linear_rmse, 2))

Linear Regression MAE: 31.16
Linear Regression RMSE: 40.21

In [35]:
from sklearn.ensemble import RandomForestRegressor

print("Random Forest library ready ✅")

Random Forest library ready ✅

In [36]:
# Create Random Forest model

rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

print("Random Forest model created ✅")

Random Forest model created ✅

In [37]:
# Train Random Forest

rf_model.fit(X_train, y_train)

print("Random Forest trained successfully! ✅")

Random Forest trained successfully! ✅

In [38]:
# Make predictions on test data

rf_predictions = rf_model.predict(X_test)

print("Random Forest predictions created:", len(rf_predictions))

Random Forest predictions created: 555

In [39]:
# Evaluate Random Forest

rf_mae = mean_absolute_error(
    y_test,
    rf_predictions
)

rf_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        rf_predictions
    )
)

print("Random Forest MAE:", round(rf_mae, 2))
print("Random Forest RMSE:", round(rf_rmse, 2))

Random Forest MAE: 32.95
Random Forest RMSE: 42.31